### ISSUE TITLE
Sass task requires input to be as resource

### ISSUE THREAD

**Issue by kirillsalykin** [mbuczko/revolt#2]
`revolt.tasks.sass` requires changed file to be a resource, I think there is no need for this, just reading file should enough.

Also, input and output relative paths are the same, which I think makes them to much coupled.

It is possible to have more then 1 main.css, for instance `www.css`, `app.css` and `admin.css`.
I propose to have a rule if sass file doesnt start with `_` then it should be compiled to standalone file.

For instance we have these main styles: `www.scss`, `app.scss` and `admin.scss`, they all can use `_grid.scss`, `_forms.scss` etc. It is expected only `www.css`, `app.css` and `admin.css` to compiled. (Similar to https://github.com/Deraen/sass4clj)

I think sass task should accept output directory relative to `target` as param (not resources as it is now) and on file change - just read changed file directly (not from resources) and compile if needed.

Hope all clear, thanks!

**Comment by mbuczko** [comment]
Hey, thanks for suggestion. Actually I decided to go resource-oriented path simply because most of the time I didn't have any need to change the output path :)

Anyway, I will try to reimplement this task later this week to make output path an optional parameter.

**Comment by mbuczko** [comment]
ok, it took a long time but it's already there (in version 1.0.0).

now, `sass` task takes a `source-path` and `output-dir` and compiles every file inside which does not start with "_".

in case of any problems, please take a look at [revolt-edge](https://github.com/mbuczko/revolt-edge) first.
