### ISSUE TITLE
tools.deps api changes

### ISSUE THREAD

**Issue by puredanger** [mbuczko/revolt#3]
Just wanted to drop a note that the newest version of tools.deps.alpha contains some api changes (moving towards getting out of alpha). So when you bump to tools.deps.alpha >= 0.9.745, you'll need to change your use of clojure.tools.deps.alpha.reader/slurp-deps - that is now in clojure.tools.deps.alpha.

**Comment by mbuczko** [comment]
adjusted in in https://github.com/mbuczko/revolt/commit/eb2b8c0c4f3d3b401b6db1e93a1e0b88e885bed3.

thanks for letting me know about the changes in api.
